### ISSUE TITLE
reCAPTCHA succeeds but NodeBB thinks it fails.

### ISSUE THREAD

**Issue by boomzillawtf** [akhoury/nodebb-plugin-spam-be-gone#74] opened 2020-06-19 19:28 UTC
We're currently on NodeBB v1.4.0-7 (don't ask) and have Spam-Be-Gone 0.7.1 (which the ACP thinks is the latest version). When a new user tries to register and completes the Google reCAPTCHA, it succeeds:

![image](https://user-images.githubusercontent.com/13367628/85173490-582a3180-b241-11ea-9292-8aee19fbf57b.png)

However, when clicking the "Register" button, this happens:

![image](https://user-images.githubusercontent.com/13367628/85173533-73953c80-b241-11ea-8700-1f581c61e211.png)

I don't see anything in the nodebb logs regarding an error or anything.

**Comment by julianlam** [comment] 2020-06-19 20:22
Looks like a regression from my update, I wonder why it broke... I didn't change anything related to reCAPTCHA...

In any case, a workaround would be to set up and use hCaptcha for now until a fix is developed (hCaptcha is available in the plugin now). It's not a particularly GOOD workaround, since it's a different product, but hopefully you can take advantage of it.

**Comment by phit** [comment] 2020-06-20 07:49
getting the  same issue on 0.7.0, then realized the ACP is broken when trying to switch to hcaptcha, updating to 0.7.1 now

just figured id let you know your 0.7.1 update didnt cause this

**Comment by julianlam** [comment] 2020-06-22 15:26
Fix released in v0.7.2 of this plugin, apologies for the regression!

**Closed** 2020-06-22 15:26 UTC
Labels: bug
