### ISSUE TITLE
CAPTCHA does not always show up on cold load of /register

### ISSUE THREAD

**Issue by bpmottathai** [akhoury/nodebb-plugin-spam-be-gone#65] opened 2018-10-30 08:30 UTC
Installed plugin 0.5.5 on nodebb 1.5.3. check registration page.
http://tforum.herokuapp.com

**Comment by julianlam** [comment] 2018-10-30 13:02
Please provide more context. "Captcha heading only shows" does not mean anything in this context.

Screenshots, etc.

**Comment by bpmottathai** [comment] 2018-10-30 13:20
http://malayalam.herokuapp.com/register
![](https://i.postimg.cc/J7B75Z12/Screenshot-20181030-184800.png)
 installed plugin by npm install method and deploy to heroku from local directory. I installed it and set API key and secret key.restart forum. Once it appears the captcha. Later when I check it disappeared.

**Comment by julianlam** [comment] 2018-10-30 20:04
@akhoury https://webmasters.googleblog.com/2018/10/introducing-recaptcha-v3-new-way-to.html

Any chance plugin automatically switched to v3?

**Comment by akhoury** [comment] 2018-10-31 05:59
Both versions use the same "script" https://www.google.com/recaptcha/api.js

https://developers.google.com/recaptcha/docs/v3
https://developers.google.com/recaptcha/docs/invisible (v2)

but i'm using v2 JS Api for sure https://developers.google.com/recaptcha/docs/invisible#js_api 
here: https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/public/js/scripts.js#L4-L17

**Comment by akhoury** [comment] 2018-10-31 06:00
it's not loading at all, that's just the label.. look at the network tab

![screen shot 2018-10-31 at 1 58 34 am](https://user-images.githubusercontent.com/1398375/47768995-a37c7e80-dcb0-11e8-9e7b-b36c2e0effea.png)

vs on the nodebb community register page.

![screen shot 2018-10-31 at 1 59 10 am](https://user-images.githubusercontent.com/1398375/47768996-a37c7e80-dcb0-11e8-8d68-3f3ab9fb2f06.png)

**Comment by akhoury** [comment] 2018-10-31 06:02
wait, now i can see it :/ 
![screen shot 2018-10-31 at 2 02 29 am](https://user-images.githubusercontent.com/1398375/47769119-10901400-dcb1-11e8-812f-45624b4574ac.png)

**Comment by akhoury** [comment] 2018-10-31 06:03
@julianlam is it possible it's missing the `action:ajaxify.end` event? is that a reliable event?

https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/public/js/scripts.js#L20

**Comment by bpmottathai** [comment] 2018-10-31 06:10
@akhoury 
Try it
http://malayalam.herokuapp.com/register
Plugin version 0.5.0
Nodebb version 1.5.3
Using check box reCAPTCHA

**Comment by julianlam** [comment] 2018-10-31 15:27
@akhoury Hmm, it used to be, but things got a little less reliable when we moved the scripts to the footer, maybe that's why. Race condition...

**Comment by akhoury** [comment] 2018-11-12 10:10
@julianlam sorry for the delay here, i must have marked this email as read while asleep. ok so, what is a reliable hook that we can try.

**Comment by julianlam** [comment] 2018-11-12 16:36
I personally think it's a core issue that should be fixed. `action:ajaxify.end` should fire on all page loads, so the race condition ought to be addressed. I'll take a look.

**Comment by julianlam** [comment] 2018-11-12 20:59
I can't actually replicate this issue, it always works on my local environment, and always shows up on community.nodebb.org. Shows up all the time on http://malayalam.herokuapp.com/register as well, so I'm at a loss right now.

**Comment by johnking** [comment] 2018-12-14 00:14
@julianlam I have the same,

**Comment by akhoury** [comment] 2018-12-14 15:31
that does sound like a race condition.

**Comment by johnking** [comment] 2018-12-14 15:57
looks like a free-tier heroku hosting service can help us to find some bugs :-). 

@julianlam you may use heroku hosting to recover the issue I mentioned and troubleshoot the race condition bug, it is easy to recover but you may have to wait for a while though.

Right now, I have to deactivate captcha plugin otherwise new users could not register because they could not tick the captcha box.

**Comment by akhoury** [comment] 2019-05-16 14:15
@julianlam were you able to reproduce the issue? or is it still intermittent

**Comment by floufille** [comment] 2019-05-16 17:53
Hello,

On: https://community.nodebb.org/
If you go on "register" (recaptcha appears), then "users", then "register" (recapatch not appears).
If you continue to go to "users" then "register", the recapatcha never appears.

If you refresh (with F5) the page https://community.nodebb.org/register It's appears.

I have the same comportement on my nodebb instance.

**Comment by barisusakli** [comment] 2019-05-16 18:49
@bpmottathai let use know if you can reproduce with 0.6.3

**Closed by barisusakli** 2019-05-16 18:49 UTC
